-- Create table for storing user's selected politicians
create table public.meus_parlamentares (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  politician_id int not null,
  politician_name text,
  politician_type text check (politician_type in ('camara', 'senado')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.meus_parlamentares enable row level security;

-- Create policies
create policy "Users can view their own selections"
  on public.meus_parlamentares for select
  using (auth.uid() = user_id);

create policy "Users can insert their own selections"
  on public.meus_parlamentares for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own selections"
  on public.meus_parlamentares for delete
  using (auth.uid() = user_id);
